### ISSUE TITLE
Add bps retained to wavefront

### ISSUE THREAD

**Issue by smabie** [codehard-labs/wavefront-interface#2]
Bps retained is an important metric in any HFT system. In our case we can use the simple formula:

```
bps_retained = P/L / (Total Volume / 2)
```

Let's add it to the frontend:
![image](https://user-images.githubusercontent.com/1126907/205418886-aab471a9-c7af-40be-b0d5-8cbf2eb6605a.png)

**Comment by codehard-labs** [comment]
Couple quick things here:

- I think the current trading volume is 3x a trade's USD value if it's a triangular trade, so maybe we would want to handle this.
- let's make this a 3x3 grid or otherwise it will trigger my serious OCD whenever im opening the panel. 
- I would suggest to also add overall delta exposure (we already have % held in USD so this is easy).
- cant think of the last one for now, any suggestion?
